print("Muslim objections and what they really mean: ")
print("\"You have to read it in Arabic\"")
print("What it really means: ", end="")
print("\"Yep, it's bad. Let's hope it sounds better in Arabic...", end="")
print("Better yet, let's hope they don't read Arabic to ask further questions.\"")
print("\"That hadith isn't authentic!\"")
print("What it really means: ", end="")
print("\"Dear God, this hadith better be false.\"")
print("\"David Wood is a liar!\"")
print("What it really means: ", end="")
print("\"I am too lazy to look up if what he is saying actually is in my Quran.\"")
print("\"Yeah well, your Bible says this ....\"")
print("What is really means: ", end="")
print("\"I just admitted the Quran has problems that can't be justified ", end="")
print("so I will divert and point at the the bible ", end="")
print("not realizing I'm further shooting myself in the foot\"")
print("\"You can't trust white people like David Wood, ", end="")
print("you have to go to an Imam for information about the Quran\"")
print("What it really means: ", end="")
print("\"I am a sheep that can't discern anything, ", end="")
print("and I likely don't know what taqiyya is.\"")
print("\"That's not what Allah meant. What he really meant to say was...\"")
print("What it really means: ", end="")
print("\"I'm going to completely reinterpret this verse ", end="")
print("because the clear meaning is detrimental to Islam\"")
print("lol :)")
